# Generated by Django 2.0 on 2017-12-30 15:18

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Unique account identifier. May only contain letters, numbers, underscores and hyphens.', unique=True)),
                ('currency', djmoney.models.fields.CurrencyField(choices=[('XBT', 'Bitcoin'), ('EUR', 'Euro'), ('PHP', 'Philippine Peso'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('balance', djmoney.models.fields.MoneyField(currency_field_name='currency', decimal_places=18, default=Decimal('0.0'), default_currency='USD', editable=False, max_digits=36)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Unique string that identifies owner. May only contain letters, numbers, underscores and hyphens.', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(help_text="Account owner's ID.", on_delete=django.db.models.deletion.PROTECT, to='payments.Owner'),
        ),
    ]
