# Generated by Django 2.0 on 2017-12-31 12:48

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', djmoney.models.fields.CurrencyField(choices=[('XBT', 'Bitcoin'), ('EUR', 'Euro'), ('PHP', 'Philippine Peso'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('amount', payments.models.MoneyField(currency_field_name='currency', decimal_places=18, default=Decimal('0.0'), default_currency='USD', max_digits=36)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('unique_id', models.CharField(max_length=64, unique=True)),
                ('source_balance_before', payments.models.MoneyField(currency_field_name='currency', decimal_places=18, default=None, default_currency='USD', max_digits=36, null=True)),
                ('destination_balance_before', payments.models.MoneyField(currency_field_name='currency', decimal_places=18, default=None, default_currency='USD', max_digits=36, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=payments.models.MoneyField(currency_field_name='currency', decimal_places=18, default=Decimal('0.0'), default_currency='USD', editable=False, max_digits=36),
        ),
        migrations.AddField(
            model_name='payment',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_from', to='payments.Account'),
        ),
        migrations.AddField(
            model_name='payment',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_to', to='payments.Account'),
        ),
    ]
