# Generated by Django 2.0 on 2017-12-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_payment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='confirmed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
